language: ruby

rvm:
  - "1.8.7"
  - "1.9.3"
  - "2.0.0"
  - "jruby-19mode"

gemfile:
  - "gemfiles/rack.gemfile"
  - "gemfiles/rails-3.0.gemfile"
  - "gemfiles/rails-3.1.gemfile"
  - "gemfiles/rails-3.2.gemfile"
  - "gemfiles/rails-4.0.gemfile"

matrix:
  allow_failures:
    - rvm: "1.8.7"

script: "RAILS_ENV=test bundle exec rspec spec"
