language: ruby

rvm:
  - 1.9.3
  - 2.0.0
  - jruby-19mode

gemfile:
  - gemfiles/3.0.gemfile
  - gemfiles/3.1.gemfile
  - gemfiles/3.2.gemfile
  - gemfiles/4.0.gemfile

script: RAILS_ENV=test bundle exec rspec spec
