language: ruby

rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - ree
  - ruby-head
  - jruby-18mode
  - jruby-19mode
  - jruby-head

gemfile:
  - gemfiles/3.0.gemfile
  - gemfiles/3.1.gemfile
  - gemfiles/3.2.gemfile
  - gemfiles/4.0.gemfile
  - gemfiles/edge.gemfile

matrix:
  exclude:
    - rvm: 1.8.7
      gemfile: gemfiles/edge.gemfile
  allow_failures:
    - 1.8.7
    - gemfile: gemfiles/edge.gemfile

script: RAILS_ENV=test bundle exec rspec spec
